### ISSUE TITLE
Let users customize some branding with server-wide configuration settings 

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-GithubFeedbackForm#6]
Right now, Suffolk uses the stock feedback form with a very light customization. But the customization happens in the YAML. It might be more convenient to allow organizations to customize this branding in the server-wide config. We can integrate these settings with the Dashboard.

Here's the customized YAML for Suffolk as a jumping off point:

```yaml
---
include:
  - docassemble.GithubFeedbackForm:feedback.yml
---
metadata:
  title: CourtFormsOnline Feedback Form
  short title: Feedback
---
code: |
  al_feedback_form_title = "CourtFormsOnline Feedback Form"  
---
code: |
  # This email will be used ONLY if there is no valid GitHub config
  al_error_email = "massaccess@suffolk.edu"  
---
template: al_how_to_get_legal_help
content: |
  If you need more help, these are free resources:
  - For help with a non-criminal legal problem in Massachusetts, use the 
  [Massachusetts Legal Resource Finder](http://masslegalhelp.org/find-legal-aid)
  - If your income is low enough, try the [Mass Legal Answers Online](http://masslao.org/) website where volunteer lawyers answer questions
  about your personal civil legal problems.
```
